### ISSUE TITLE
DCS BIOS 0.10.0 & MiG-19

### ISSUE THREAD

**Issue by Mabo72** [dcs-bios/dcs-bios#210]
Hi,

DcsBios::RotaryEncoder ark5FreqZune("ARK5_FREQ_ZUNE", "-3200", "+3200", PIN_A, PIN_B);

works incorrectly:
you have to rotate both ways alternately - the dial only rotates left

**Comment by WarLord211** [comment]
fix is uploaded

**Comment by Mabo72** [comment]
Still not working properly: the crank turns but the scale does not move

**Comment by WarLord211** [comment]
Ok here is a test:
https://www.dropbox.com/s/g9r4im270srnfjo/MiG-19P.lua?dl=0

i cant try it for myself i dont have the module.
And i fixed the typo from this switch to :   ARK5_FREQ_TUNE

**Comment by WarLord211** [comment]
Ok here is a test:
 https://www.dropbox.com/s/g9r4im270srnfjo/MiG-19P.lua?dl=0
 
 i cant try it for myself i dont have the module.
 And i fixed the typo from this switch to : ARK5_FREQ_TUNE

pls give feedback

**Comment by Mabo72** [comment]
Now the crank does not turn at all

**Comment by WarLord211** [comment]
ok i changed it back.
pls try again. (link above)

And pls try "GIK-1 Course Selector" and "Barometric Altimeter Setting" these programmed the same way. so maybe i find something. (its hard to programm it without testing it for myself)

 i found some other errors too

**Comment by Mabo72** [comment]
The GIK-1 and barometric altimeter works well.
But ARK5 - still does not work properly: the crank turns, but the scale does not move

movie: https://drive.google.com/open?id=1hJso9UJaaHwVQTE28jUuTCsYrc9oy8Qe

**Comment by WarLord211** [comment]
OK after some research: this cant be fixed from BIOS side.

The Problem is in the Plane itself. if you try this via keybinding you got the same result.

here the bug treat: https://forums.eagle.ru/showthread.php?t=242058&page=2

im sorry for that

**Comment by Mabo72** [comment]
OK, thank you for the information

**Comment by WarLord211** [comment]
should fixed in the latest beta of DCS

**Comment by Mabo72** [comment]
I confirm - now it works OK.
